In [1]:
# googleドライブのマウント
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# sys.pathの設定
import sys
sys.path.append('/content/drive/My Drive/DNN_code')

In [4]:
# importと関数定義
import numpy as np
from common import functions

def print_vec(text, vec):
  print('***' + text + '***')
  print(vec)
  print('shape:' +str(vec.shape))
  print('')

順伝播（単層・単ユニット）

In [5]:
# 重み
W = np.array([[0.1], [0.2]])

# 配列の初期化
print(np.zeros(2))
print(np.ones(2))
print(np.random.rand(2))
print(np.random.randint(5, size=(2)))

[0. 0.]
[1. 1.]
[0.79107647 0.46131529]
[4 3]


In [6]:
print_vec('重み', W)

***重み***
[[0.1]
 [0.2]]
shape:(2, 1)



In [9]:
# バイアス
b = np.array(0.5)
print_vec('バイアス', b)

***バイアス***
0.5
shape:()



In [10]:
# 入力値
x = np.array([2,3])
print_vec('入力', x)

# 総入力
u = np.dot(x, W) + b
print_vec('総入力', u)

# 中間層出力
z = functions.relu(u)
print_vec('中間層出力', z)

***入力***
[2 3]
shape:(2,)

***総入力***
[1.3]
shape:(1,)

***中間層出力***
[1.3]
shape:(1,)



順伝播（単層・複数ユニット）

In [11]:
# 重み
W = np.array([
              [0.1, 0.2, 0.3, 0],
              [0.2, 0.3, 0.4, 0.5],
              [0.3, 0.4, 0.5, 1]
])

print_vec('重み', W)

***重み***
[[0.1 0.2 0.3 0. ]
 [0.2 0.3 0.4 0.5]
 [0.3 0.4 0.5 1. ]]
shape:(3, 4)



In [12]:
# バイアス
b = np.array([0.1, 0.2, 0.3])
print_vec('バイアス', b)

***バイアス***
[0.1 0.2 0.3]
shape:(3,)



In [14]:
# 入力値
x = np.array([1.0, 5.0, 2.0, -1.0])
print_vec('入力', x)

# 総入力
u = np.dot(W, x) + b
print_vec('総入力', u)

# 中間層出力
z = functions.sigmoid(u)
print_vec('中間層出力', z)

***入力***
[ 1.  5.  2. -1.]
shape:(4,)

***総入力***
[1.8 2.2 2.6]
shape:(3,)

***中間層出力***
[0.85814894 0.90024951 0.93086158]
shape:(3,)



順伝播（3層・複数ユニット）

In [15]:
# 重みとバイアスを定義
def init_network():
    print("##### ネットワークの初期化 #####")
    network = {}
    
    input_layer_size = 3
    hidden_layer_size_1 = 10
    hidden_layer_size_2 = 5
    output_layer_size = 4

    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size_1)
    network['W2'] = np.random.rand(hidden_layer_size_1, hidden_layer_size_2)
    network['W3'] = np.random.rand(hidden_layer_size_2, output_layer_size)

    network['b1'] = np.random.rand(hidden_layer_size_1)
    network['b2'] = np.random.rand(hidden_layer_size_2)
    network['b3'] = np.random.rand(output_layer_size)

    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("重み3", network['W3'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )
    print_vec("バイアス3", network['b3'] )

    return network

# 順伝播処理
def forward(network, x):
    
    print("##### 順伝播開始 #####")

    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1
    
    # 1層の総出力
    z1 = functions.relu(u1)
    
    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 2層の総出力
    z2 = functions.relu(u2)

    # 出力層の総入力
    u3 = np.dot(z2, W3) + b3
    
    # 出力層の総出力
    y = u3
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力2", z2)
    print("出力合計: " + str(np.sum(z1)))

    return y, z1, z2

# 入力値
x = np.array([1., 2., 4.])
print_vec("入力", x)

# ネットワークの初期化
network =  init_network()

y, z1, z2 = forward(network, x)

***入力***
[1. 2. 4.]
shape:(3,)

##### ネットワークの初期化 #####
***重み1***
[[0.78251967 0.39883545 0.79222737 0.32852705 0.45823971 0.34146972
  0.47480997 0.44342556 0.19643176 0.88463561]
 [0.86211357 0.56344888 0.25063782 0.44320972 0.47316972 0.48813604
  0.57692871 0.87391458 0.34737003 0.71652052]
 [0.75166644 0.21657572 0.49904055 0.78164992 0.2590353  0.86183661
  0.70360344 0.46937142 0.50670326 0.9608542 ]]
shape:(3, 10)

***重み2***
[[0.90982074 0.97311324 0.8350351  0.37518575 0.10874109]
 [0.39655402 0.020687   0.57451938 0.06690921 0.52709473]
 [0.96633477 0.36849358 0.39616173 0.88868679 0.39957161]
 [0.43523702 0.15821765 0.0551468  0.48736298 0.67044193]
 [0.23277173 0.05113038 0.31267921 0.51490669 0.79510735]
 [0.44704844 0.58891599 0.22372962 0.23271102 0.28250982]
 [0.31498952 0.49086292 0.92625007 0.66605316 0.01620713]
 [0.21109524 0.4047035  0.85087175 0.16384431 0.07407167]
 [0.49282564 0.91266281 0.79052497 0.3066093  0.51075645]
 [0.68142549 0.42887503 0.54078926 0.61285

多クラス分類（2-3-4ネットワーク）

In [16]:
# 重みとバイアスを設定
def init_network():
    print("##### ネットワークの初期化 #####")

    network = {}

    input_layer_size = 3
    hidden_layer_size = 50
    output_layer_size = 6

    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size)
    network['W2'] = np.random.rand(hidden_layer_size, output_layer_size)

    network['b1'] = np.random.rand(hidden_layer_size)
    network['b2'] = np.random.rand(output_layer_size)
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

In [17]:
# 順伝播処理
# x：入力値
def forward(network, x):
    print("##### 順伝播開始 #####")
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1

    # 1層の総出力
    z1 = functions.relu(u1)

    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 出力値
    y = functions.softmax(u2)
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力", y)
    print("出力合計: " + str(np.sum(y)))
        
    return y, z1

# 入力値
x = np.array([1., 2., 3.])

# 目標出力
d = np.array([0, 0, 0, 1, 0, 0])

# ネットワークの初期化
network =  init_network()

# 出力
y, z1 = forward(network, x)

# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)

##### ネットワークの初期化 #####
***重み1***
[[4.80136854e-01 1.11136308e-01 1.68824655e-01 7.48094013e-01
  5.40187477e-01 2.97718124e-01 6.58899682e-01 2.91786642e-01
  5.59890364e-01 5.67942132e-01 6.74828472e-02 4.84629112e-01
  2.12401010e-01 1.48159412e-01 2.95383391e-01 7.06460973e-01
  3.60444820e-01 6.91215378e-01 6.04126752e-01 7.23265095e-01
  7.46803031e-01 8.39532678e-02 3.97591740e-01 1.32434478e-01
  5.59120796e-01 1.03789272e-01 8.79032947e-01 1.01661996e-01
  1.64249201e-01 3.99490316e-01 5.32876875e-01 3.15267120e-01
  6.42374599e-01 8.89809863e-01 8.21665315e-01 6.00874148e-01
  8.02644748e-01 3.18583650e-01 8.04865874e-01 8.59084821e-01
  2.14444221e-01 6.29554164e-01 1.47344110e-01 1.82222233e-01
  1.62701006e-01 5.97722715e-01 3.60037952e-01 1.81841430e-01
  2.88071329e-01 8.84037008e-01]
 [6.40848204e-01 9.58541070e-01 6.91109122e-01 4.01647808e-01
  9.18957351e-02 1.68332722e-01 8.72414839e-01 8.80922119e-02
  3.55535917e-01 9.46392701e-01 4.50987629e-01 1.95257045e-01
  9.

回帰(2-3-2ネットワーク)


In [18]:
# 重みとバイアスの初期値を設定
def init_network():
  network = {}

  input_layer_size = 3
  hidden_layer_size = 50
  output_layer_size = 2

  network['W1'] = np.random.rand(input_layer_size, hidden_layer_size)
  network['W2'] = np.random.rand(hidden_layer_size, output_layer_size)

  network['b1'] = np.random.rand(hidden_layer_size)
  network['b2'] = np.random.rand(output_layer_size)

  return network

# 順伝播処理
def forward(network, x):
  W1, W2 = network['W1'], network['W2']
  b1, b2 = network['b1'], network['b2']

  # 隠れ層の総入力
  u1 = np.dot(x, W1) + b1
  # 隠れ層の総出力
  z1 = functions.relu(u1)
  # 出力層の総入力
  u2 = np.dot(z1, W2) + b2
  # 出力層の総出力
  y = u2

  print_vec('総入力1', u1)
  print_vec('中間層出力1', z1)
  print_vec('総入力2', u2)
  print_vec('出力', y)
  print('出力合計:' + str(np.sum(y)))

  return y, z1




In [19]:
# 入力値
x = np.array([1., 2., 3.])
network = init_network()
y, z1 = forward(network, x)

# 目標値出力
d = np.array([2., 4.])
# 誤差
loss = functions.mean_squared_error(d, y)


print_vec('中間層出力', z1)
print_vec('出力', y)
print_vec('訓練データ', d)
print_vec('誤差', loss)


***総入力1***
[5.23451509 4.44331631 1.3277686  1.93828013 2.82743859 4.03805156
 2.63270648 2.14078396 2.95945016 3.87270422 4.12608171 3.46736289
 0.54773651 5.02748574 3.40039917 2.55722124 3.54748798 4.14752354
 3.19044962 2.33435688 3.3207592  3.27244447 4.8080904  3.40832176
 4.2485138  4.03131124 5.07443024 3.3356788  3.42265417 3.46248357
 4.13203439 5.43333342 2.78596756 3.12488577 5.37876591 2.14601461
 2.87308507 3.04311166 5.01939396 3.81084537 3.60608626 4.24148213
 3.48196879 4.13059671 4.94904874 3.31867898 4.48475921 3.4668717
 3.47349541 3.84728114]
shape:(50,)

***中間層出力1***
[5.23451509 4.44331631 1.3277686  1.93828013 2.82743859 4.03805156
 2.63270648 2.14078396 2.95945016 3.87270422 4.12608171 3.46736289
 0.54773651 5.02748574 3.40039917 2.55722124 3.54748798 4.14752354
 3.19044962 2.33435688 3.3207592  3.27244447 4.8080904  3.40832176
 4.2485138  4.03131124 5.07443024 3.3356788  3.42265417 3.46248357
 4.13203439 5.43333342 2.78596756 3.12488577 5.37876591 2.14601461
 2

二値分類(2-3-1ネットワーク）

In [20]:
# 重みとバイアスの初期値を設定
def init_network():
  network = {}
  network['W1'] = np.array([
    [0.1, 0.3, 0.5, 0.1, 0.3, 0.5, 0.1, 0.3, 0.5, 0.1],
    [0.1, 0.3, 0.5, 0.1, 0.3, 0.5, 0.1, 0.3, 0.5, 0.1],
    [0.1, 0.3, 0.5, 0.1, 0.3, 0.5, 0.1, 0.3, 0.5, 0.1],
    [0.1, 0.3, 0.5, 0.1, 0.3, 0.5, 0.1, 0.3, 0.5, 0.1],
    [0.1, 0.3, 0.5, 0.1, 0.3, 0.5, 0.1, 0.3, 0.5, 0.1]
  ])

  network['W2'] = np.random.rand(10, 20)
  network['W3'] = np.random.rand(20, 1)

  network['b1'] = np.random.rand(10)
  network['b2'] = np.random.rand(20)
  network['b3'] = np.random.rand(1)


  return network

# 順伝播処理
def forward(network, x):
  W1, W2, W3 = network['W1'], network['W2'], network['W3']
  b1, b2, b3 = network['b1'], network['b2'], network['b3']

  # 隠れ層1の総入力
  u1 = np.dot(x, W1) + b1
  # 隠れ層1の総出力
  z1 = functions.relu(u1)
  # 隠れ層2の総入力
  u2 = np.dot(z1, W2) + b2
  # 隠れ層2の総出力
  z2 = functions.relu(u2)

  u3 = np.dot(z2, W3) + b3
  z3 = functions.sigmoid(u3)
  y = z3

  print_vec('総入力1', u1)
  print_vec('中間層出力1', z1)
  print_vec('総入力2', u2)
  print_vec('出力', y)
  print('出力合計:' + str(np.sum(y)))

  return y, z1

In [21]:
# 入力値
x = np.array([1., 2., 2., 4., 5.])
network = init_network()
y, z1 = forward(network, x)

# 目標値出力
d = np.array([1])
# 誤差
loss = functions.cross_entropy_error(d, y)


print_vec('中間層出力', z1)
print_vec('出力', y)
print_vec('訓練データ', d)
print_vec('誤差', loss)

***総入力1***
[1.48029212 4.20586681 7.88018177 1.9107781  4.26763496 7.12386716
 2.20457495 4.83024317 7.52934023 2.01046324]
shape:(10,)

***中間層出力1***
[1.48029212 4.20586681 7.88018177 1.9107781  4.26763496 7.12386716
 2.20457495 4.83024317 7.52934023 2.01046324]
shape:(10,)

***総入力2***
[24.20475353 30.34343531 20.57985647 21.17402302 18.29227409 18.58074887
 17.83878733 13.38331028 17.353876   21.00569322 24.89301086 23.1803916
 30.26907926 17.60138304 25.33681275 28.1675874  27.90220584 15.93121474
 16.98996557 22.57055006]
shape:(20,)

***出力***
[1.]
shape:(1,)

出力合計:1.0
***中間層出力***
[1.48029212 4.20586681 7.88018177 1.9107781  4.26763496 7.12386716
 2.20457495 4.83024317 7.52934023 2.01046324]
shape:(10,)

***出力***
[1.]
shape:(1,)

***訓練データ***
[1]
shape:(1,)

***誤差***
-9.999999505838704e-08
shape:()

