In [2]:
# googleドライブのマウント
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# sys.pathの設定
import sys
sys.path.append('/content/drive/My Drive/DNN_code')

In [4]:
# importと関数定義
import numpy as np
from common import functions

def print_vec(text, vec):
  print('***' + text + '***')
  print(vec)
  print('')

順伝播（単層・単ユニット）

In [5]:
# 重み
W = np.array([[0.1], [0.2]])

# 配列の初期化
print(np.zeros(2))
print(np.ones(2))
print(np.random.rand(2))
print(np.random.randint(5, size=(2)))

[0. 0.]
[1. 1.]
[0.61286752 0.22149673]
[4 4]


In [6]:
print_vec('重み', W)

***重み***
[[0.1]
 [0.2]]



In [7]:
# バイアス
b = 0.5
print_vec('バイアス', b)

print(np.random.rand()) # 0~1のランダム数値
print((np.random.rand() * 10) -5)  # -5~5のランダム数値

***バイアス***
0.5

0.9941068760451874
-0.15147462677435009


In [8]:
# 入力値
x = np.array([2,3])
print_vec('入力', x)

# 総入力
u = np.dot(x, W) + b
print_vec('総入力', u)

# 中間層出力
z = functions.relu(u)
print_vec('中間層出力', z)

***入力***
[2 3]

***総入力***
[1.3]

***中間層出力***
[1.3]



順伝播（単層・複数ユニット）

In [9]:
# 重み
W = np.array([
              [0.1, 0.2, 0.3],
              [0.2, 0.3, 0.4],
              [0.3, 0.4, 0.5],
              [0.4, 0.5, 0.6]
])

print_vec('重み', W)

***重み***
[[0.1 0.2 0.3]
 [0.2 0.3 0.4]
 [0.3 0.4 0.5]
 [0.4 0.5 0.6]]



In [10]:
# バイアス
b = np.array([0.1, 0.2, 0.3])
print_vec('バイアス', b)

***バイアス***
[0.1 0.2 0.3]



In [11]:
# 入力値
x = np.array([1.0, 5.0, 2.0, -1.0])
print_vec('入力', x)

# 総入力
u = np.dot(x, W) + b
print_vec('総入力', u)

# 中間層出力
z = functions.sigmoid(u)
print_vec('中間層出力', z)

***入力***
[ 1.  5.  2. -1.]

***総入力***
[1.4 2.2 3. ]

***中間層出力***
[0.80218389 0.90024951 0.95257413]



順伝播（3層・複数ユニット）

In [12]:
# 重みとバイアスを定義
def init_network():
  print("##### ネットワークの初期化 #####")
  network = {}
        
  network['W1'] = np.array([
      [0.1, 0.3, 0.5],
      [0.2, 0.4, 0.6]
  ])
  network['W2'] = np.array([
      [0.1, 0.4],
      [0.2, 0.5],
      [0.3, 0.6]
  ])
  network['W3'] = np.array([
      [0.1, 0.3],
      [0.2, 0.4]
  ])
  network['b1'] = np.array([0.1, 0.2, 0.3])
  network['b2'] = np.array([0.1, 0.2])
  network['b3'] = np.array([1, 2])

  print_vec("重み1", network['W1'] )
  print_vec("重み2", network['W2'] )
  print_vec("重み3", network['W3'] )
  print_vec("バイアス1", network['b1'] )
  print_vec("バイアス2", network['b2'] )
  print_vec("バイアス3", network['b3'] )

  return network

# 順伝播処理
def forward(network, x):
    
  print("##### 順伝播開始 #####")

  W1, W2, W3 = network['W1'], network['W2'], network['W3']
  b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
  # 1層の総入力
  u1 = np.dot(x, W1) + b1
    
  # 1層の総出力
  z1 = functions.relu(u1)
    
  # 2層の総入力
  u2 = np.dot(z1, W2) + b2
    
  # 2層の総出力
  z2 = functions.relu(u2)

  # 出力層の総入力
  u3 = np.dot(z2, W3) + b3
    
  # 出力層の総出力
  y = u3
    
  print_vec("総入力1", u1)
  print_vec("中間層出力1", z1)
  print_vec("総入力2", u2)
  print_vec("出力2", z2)
  print("出力合計: " + str(np.sum(z1)))

  return y, z1, z2

# 入力値
x = np.array([1., 2.])
print_vec("入力", x)

# ネットワークの初期化
network =  init_network()

y, z1, z2 = forward(network, x)
print('出力y', y)

***入力***
[1. 2.]

##### ネットワークの初期化 #####
***重み1***
[[0.1 0.3 0.5]
 [0.2 0.4 0.6]]

***重み2***
[[0.1 0.4]
 [0.2 0.5]
 [0.3 0.6]]

***重み3***
[[0.1 0.3]
 [0.2 0.4]]

***バイアス1***
[0.1 0.2 0.3]

***バイアス2***
[0.1 0.2]

***バイアス3***
[1 2]

##### 順伝播開始 #####
***総入力1***
[0.6 1.3 2. ]

***中間層出力1***
[0.6 1.3 2. ]

***総入力2***
[1.02 2.29]

***出力2***
[1.02 2.29]

出力合計: 3.9
出力y [1.56  3.222]


多クラス分類（2-3-4ネットワーク）

In [13]:
# 重みとバイアスを設定
def init_network():
  print("##### ネットワークの初期化 #####")

  network = {}
  network['W1'] = np.array([
      [0.1, 0.3, 0.5],
      [0.2, 0.4, 0.6]
  ])
  network['W2'] = np.array([
      [0.1, 0.4, 0.7, 1.0],
      [0.2, 0.5, 0.8, 1.1],
      [0.3, 0.6, 0.9, 1.2]
  ])
  network['b1'] = np.array([0.1, 0.2, 0.3])
  network['b2'] = np.array([0.1, 0.2, 0.3, 0.4])
    
  print_vec("重み1", network['W1'] )
  print_vec("重み2", network['W2'] )
  print_vec("バイアス1", network['b1'] )
  print_vec("バイアス2", network['b2'] )

  return network

In [14]:
# 順伝播処理
# x：入力値
def forward(network, x):
  print("##### 順伝播開始 #####")
  W1, W2 = network['W1'], network['W2']
  b1, b2 = network['b1'], network['b2']
    
  # 1層の総入力
  u1 = np.dot(x, W1) + b1

  # 1層の総出力
  z1 = functions.relu(u1)

  # 2層の総入力
  u2 = np.dot(z1, W2) + b2
    
  # 出力値
  y = functions.softmax(u2)
    
  print_vec("総入力1", u1)
  print_vec("中間層出力1", z1)
  print_vec("総入力2", u2)
  print_vec("出力", y)
  print("出力合計: " + str(np.sum(y)))
        
  return y, z1

# 入力値
x = np.array([1., 2.])

# 目標出力
d = np.array([0, 0, 0, 1])

# ネットワークの初期化
network =  init_network()

# 出力
y, z1 = forward(network, x)

# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)

##### ネットワークの初期化 #####
***重み1***
[[0.1 0.3 0.5]
 [0.2 0.4 0.6]]

***重み2***
[[0.1 0.4 0.7 1. ]
 [0.2 0.5 0.8 1.1]
 [0.3 0.6 0.9 1.2]]

***バイアス1***
[0.1 0.2 0.3]

***バイアス2***
[0.1 0.2 0.3 0.4]

##### 順伝播開始 #####
***総入力1***
[0.6 1.3 2. ]

***中間層出力1***
[0.6 1.3 2. ]

***総入力2***
[1.02 2.29 3.56 4.83]

***出力***
[0.01602796 0.05707321 0.20322929 0.72366954]

出力合計: 1.0

##### 結果表示 #####
***出力***
[0.01602796 0.05707321 0.20322929 0.72366954]

***訓練データ***
[0 0 0 1]

***誤差***
0.3234202933601941



回帰(2-3-2ネットワーク)


In [15]:
# 重みとバイアスの初期値を設定
def init_network():
  network = {}
  network['W1'] = np.array([
    [0.1, 0.3, 0.5],
    [0.2, 0.4, 0.6]          
  ])
  network['W2'] = np.array([
    [0.1, 0.4],
    [0.2, 0.5],
    [0.3, 0.6]
  ])

  network['b1'] = np.array([0.1, 0.2, 0.3])
  network['b2'] = np.array([0.1, 0.2])

  return network

# 順伝播処理
def forward(network, x):
  W1, W2 = network['W1'], network['W2']
  b1, b2 = network['b1'], network['b2']

  # 隠れ層の総入力
  u1 = np.dot(x, W1) + b1
  # 隠れ層の総出力
  z1 = functions.relu(u1)
  # 出力層の総入力
  u2 = np.dot(z1, W2) + b2
  # 出力層の総出力
  y = u2

  print_vec('総入力1', u1)
  print_vec('中間層出力1', z1)
  print_vec('総入力2', u2)
  print_vec('出力', y)
  print('出力合計:' + str(np.sum(y)))

  return y, z1




In [16]:
# 入力値
x = np.array([1., 2.])
network = init_network()
y, z1 = forward(network, x)

# 目標値出力
d = np.array([2., 4.])
# 誤差
loss = functions.mean_squared_error(d, y)


print_vec('中間層出力', z1)
print_vec('出力', y)
print_vec('訓練データ', d)
print_vec('誤差', loss)


***総入力1***
[0.6 1.3 2. ]

***中間層出力1***
[0.6 1.3 2. ]

***総入力2***
[1.02 2.29]

***出力***
[1.02 2.29]

出力合計:3.31
***中間層出力***
[0.6 1.3 2. ]

***出力***
[1.02 2.29]

***訓練データ***
[2. 4.]

***誤差***
0.9711249999999999



二値分類(2-3-1ネットワーク）

In [17]:
# 重みとバイアスの初期値を設定
def init_network():
  network = {}
  network['W1'] = np.array([
    [0.1, 0.3, 0.5],
    [0.2, 0.4, 0.6]          
  ])
  network['W2'] = np.array([
    [0.2],
    [0.4],
    [0.6]
  ])

  network['b1'] = np.array([0.1, 0.2, 0.3])
  network['b2'] = np.array([0.1])

  return network

# 順伝播処理
def forward(network, x):
  W1, W2 = network['W1'], network['W2']
  b1, b2 = network['b1'], network['b2']

  # 隠れ層の総入力
  u1 = np.dot(x, W1) + b1
  # 隠れ層の総出力
  z1 = functions.relu(u1)
  # 出力層の総入力
  u2 = np.dot(z1, W2) + b2
  # 出力層の総出力
  y = functions.sigmoid(u2)

  print_vec('総入力1', u1)
  print_vec('中間層出力1', z1)
  print_vec('総入力2', u2)
  print_vec('出力', y)
  print('出力合計:' + str(np.sum(y)))

  return y, z1

In [18]:
# 入力値
x = np.array([1., 2.])
network = init_network()
y, z1 = forward(network, x)

# 目標値出力
d = np.array([1])
# 誤差
loss = functions.cross_entropy_error(d, y)


print_vec('中間層出力', z1)
print_vec('出力', y)
print_vec('訓練データ', d)
print_vec('誤差', loss)

***総入力1***
[0.6 1.3 2. ]

***中間層出力1***
[0.6 1.3 2. ]

***総入力2***
[1.94]

***出力***
[0.87435214]

出力合計:0.8743521434846544
***中間層出力***
[0.6 1.3 2. ]

***出力***
[0.87435214]

***訓練データ***
[1]

***誤差***
0.13427195993720972

