In [1]:
# googleドライブのマウント
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# sys.pathの設定
import sys
sys.path.append('/content/drive/My Drive/DNN_code')

In [3]:
# importと関数定義
import numpy as np
from common import functions

def print_vec(text, vec):
  print('***' + text + '***')
  print(vec)
  print('shape:' +str(vec.shape))
  print('')

順伝播（単層・単ユニット）

In [4]:
# 重み
W = np.array([[0.1], [0.2]])

# 配列の初期化
print(np.zeros(2))
print(np.ones(2))
print(np.random.rand(2))
print(np.random.randint(5, size=(2)))

[0. 0.]
[1. 1.]
[0.91720846 0.05474027]
[1 0]


In [5]:
print_vec('重み', W)

***重み***
[[0.1]
 [0.2]]
shape:(2, 1)



In [6]:
# バイアス
b = np.array(0.5)
print_vec('バイアス', b)

***バイアス***
0.5
shape:()



In [7]:
# 入力値
x = np.array([2,3])
print_vec('入力', x)

# 総入力
u = np.dot(x, W) + b
print_vec('総入力', u)

# 中間層出力
z = functions.relu(u)
print_vec('中間層出力', z)

***入力***
[2 3]
shape:(2,)

***総入力***
[1.3]
shape:(1,)

***中間層出力***
[1.3]
shape:(1,)



順伝播（単層・複数ユニット）

In [8]:
# 重み
W = np.array([
              [0.1, 0.2, 0.3, 0],
              [0.2, 0.3, 0.4, 0.5],
              [0.3, 0.4, 0.5, 1]
])

print_vec('重み', W)

***重み***
[[0.1 0.2 0.3 0. ]
 [0.2 0.3 0.4 0.5]
 [0.3 0.4 0.5 1. ]]
shape:(3, 4)



In [9]:
# バイアス
b = np.array([0.1, 0.2, 0.3])
print_vec('バイアス', b)

***バイアス***
[0.1 0.2 0.3]
shape:(3,)



In [10]:
# 入力値
x = np.array([1.0, 5.0, 2.0, -1.0])
print_vec('入力', x)

# 総入力
u = np.dot(W, x) + b
print_vec('総入力', u)

# 中間層出力
z = functions.sigmoid(u)
print_vec('中間層出力', z)

***入力***
[ 1.  5.  2. -1.]
shape:(4,)

***総入力***
[1.8 2.2 2.6]
shape:(3,)

***中間層出力***
[0.85814894 0.90024951 0.93086158]
shape:(3,)



順伝播（3層・複数ユニット）

In [11]:
# 重みとバイアスを定義
def init_network():
  print("##### ネットワークの初期化 #####")
  network = {}
    
  input_layer_size = 3
  hidden_layer_size_1 = 10
  hidden_layer_size_2 = 5
  output_layer_size = 4

  network['W1'] = np.random.rand(input_layer_size, hidden_layer_size_1)
  network['W2'] = np.random.rand(hidden_layer_size_1, hidden_layer_size_2)
  network['W3'] = np.random.rand(hidden_layer_size_2, output_layer_size)

  network['b1'] = np.random.rand(hidden_layer_size_1)
  network['b2'] = np.random.rand(hidden_layer_size_2)
  network['b3'] = np.random.rand(output_layer_size)

  print_vec("重み1", network['W1'] )
  print_vec("重み2", network['W2'] )
  print_vec("重み3", network['W3'] )
  print_vec("バイアス1", network['b1'] )
  print_vec("バイアス2", network['b2'] )
  print_vec("バイアス3", network['b3'] )

  return network

# 順伝播処理
def forward(network, x):
    
  print("##### 順伝播開始 #####")

  W1, W2, W3 = network['W1'], network['W2'], network['W3']
  b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
  # 1層の総入力
  u1 = np.dot(x, W1) + b1
    
  # 1層の総出力
  z1 = functions.relu(u1)
    
  # 2層の総入力
  u2 = np.dot(z1, W2) + b2
    
  # 2層の総出力
  z2 = functions.relu(u2)

  # 出力層の総入力
  u3 = np.dot(z2, W3) + b3
    
  # 出力層の総出力
  y = u3
    
  print_vec("総入力1", u1)
  print_vec("中間層出力1", z1)
  print_vec("総入力2", u2)
  print_vec("出力2", z2)
  print("出力合計: " + str(np.sum(z1)))

  return y, z1, z2

# 入力値
x = np.array([1., 2., 4.])
print_vec("入力", x)

# ネットワークの初期化
network =  init_network()

y, z1, z2 = forward(network, x)

***入力***
[1. 2. 4.]
shape:(3,)

##### ネットワークの初期化 #####
***重み1***
[[0.84660411 0.29780622 0.67384633 0.90942397 0.41798637 0.66152362
  0.30853705 0.7539627  0.19239472 0.94177722]
 [0.59136599 0.98102521 0.08901359 0.31792583 0.2182591  0.65499585
  0.25039299 0.78044269 0.3748927  0.19775525]
 [0.95000957 0.58865086 0.83769309 0.03659934 0.14488747 0.33644898
  0.09182168 0.86181628 0.50627127 0.70991737]]
shape:(3, 10)

***重み2***
[[0.62588479 0.59811345 0.9017805  0.98812709 0.03554788]
 [0.02666806 0.27970175 0.66476121 0.16717165 0.98479679]
 [0.17405771 0.34431914 0.95473755 0.87061498 0.14303209]
 [0.00484939 0.65487487 0.27870305 0.40281056 0.00715789]
 [0.08727467 0.516918   0.99598543 0.55604985 0.34835138]
 [0.44179339 0.51046498 0.54569857 0.64555994 0.16702266]
 [0.12742513 0.68890578 0.40941271 0.80073133 0.56602642]
 [0.19773664 0.82396037 0.07921736 0.6022079  0.01839137]
 [0.84300451 0.32023756 0.21655532 0.927807   0.15056546]
 [0.52389445 0.83896264 0.53504168 0.85928

多クラス分類（2-3-4ネットワーク）

In [12]:
# 重みとバイアスを設定
def init_network():
  print("##### ネットワークの初期化 #####")

  network = {}

  input_layer_size = 3
  hidden_layer_size = 50
  output_layer_size = 6

  network['W1'] = np.random.rand(input_layer_size, hidden_layer_size)
  network['W2'] = np.random.rand(hidden_layer_size, output_layer_size)

  network['b1'] = np.random.rand(hidden_layer_size)
  network['b2'] = np.random.rand(output_layer_size)
    
  print_vec("重み1", network['W1'] )
  print_vec("重み2", network['W2'] )
  print_vec("バイアス1", network['b1'] )
  print_vec("バイアス2", network['b2'] )

  return network

In [13]:
# 順伝播処理
# x：入力値
def forward(network, x):
  print("##### 順伝播開始 #####")
  W1, W2 = network['W1'], network['W2']
  b1, b2 = network['b1'], network['b2']
    
  # 1層の総入力
  u1 = np.dot(x, W1) + b1

  # 1層の総出力
  z1 = functions.relu(u1)

  # 2層の総入力
  u2 = np.dot(z1, W2) + b2
    
  # 出力値
  y = functions.softmax(u2)
    
  print_vec("総入力1", u1)
  print_vec("中間層出力1", z1)
  print_vec("総入力2", u2)
  print_vec("出力", y)
  print("出力合計: " + str(np.sum(y)))
        
  return y, z1

# 入力値
x = np.array([1., 2., 3.])

# 目標出力
d = np.array([0, 0, 0, 1, 0, 0])

# ネットワークの初期化
network =  init_network()

# 出力
y, z1 = forward(network, x)

# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)

##### ネットワークの初期化 #####
***重み1***
[[0.86493639 0.21914524 0.38476857 0.57643541 0.92131626 0.21695321
  0.32383106 0.37647132 0.57568158 0.09506844 0.24129212 0.37519357
  0.17413444 0.01922396 0.48634528 0.99823683 0.02059777 0.92227662
  0.93064049 0.37623766 0.80777301 0.1555759  0.08274384 0.27152201
  0.47439048 0.61450307 0.72853155 0.09946668 0.04396998 0.23210043
  0.24666201 0.25350114 0.5021245  0.14798012 0.9795813  0.16142447
  0.4647024  0.85000347 0.94099044 0.61102144 0.97325842 0.06607411
  0.06330742 0.1557093  0.81577429 0.22789869 0.89045462 0.20880876
  0.55597121 0.34457393]
 [0.00549471 0.29481098 0.46601145 0.84904292 0.42562947 0.87945304
  0.95754303 0.15487022 0.19441672 0.95868115 0.09772828 0.61305138
  0.79835524 0.80098846 0.44612459 0.24981    0.23685304 0.85180681
  0.51997148 0.14062318 0.32978129 0.64082898 0.61452028 0.18455395
  0.80504897 0.34142518 0.65705599 0.66083833 0.99382114 0.19375568
  0.43360966 0.50257397 0.44974133 0.54008223 0.00329174 0

回帰(2-3-2ネットワーク)


In [14]:
# 重みとバイアスの初期値を設定
def init_network():
  network = {}

  input_layer_size = 3
  hidden_layer_size = 50
  output_layer_size = 2

  network['W1'] = np.random.rand(input_layer_size, hidden_layer_size)
  network['W2'] = np.random.rand(hidden_layer_size, output_layer_size)

  network['b1'] = np.random.rand(hidden_layer_size)
  network['b2'] = np.random.rand(output_layer_size)

  return network

# 順伝播処理
def forward(network, x):
  W1, W2 = network['W1'], network['W2']
  b1, b2 = network['b1'], network['b2']

  # 隠れ層の総入力
  u1 = np.dot(x, W1) + b1
  # 隠れ層の総出力
  z1 = functions.relu(u1)
  # 出力層の総入力
  u2 = np.dot(z1, W2) + b2
  # 出力層の総出力
  y = u2

  print_vec('総入力1', u1)
  print_vec('中間層出力1', z1)
  print_vec('総入力2', u2)
  print_vec('出力', y)
  print('出力合計:' + str(np.sum(y)))

  return y, z1




In [15]:
# 入力値
x = np.array([1., 2., 3.])
network = init_network()
y, z1 = forward(network, x)

# 目標値出力
d = np.array([2., 4.])
# 誤差
loss = functions.mean_squared_error(d, y)


print_vec('中間層出力', z1)
print_vec('出力', y)
print_vec('訓練データ', d)
print_vec('誤差', loss)


***総入力1***
[2.67792354 4.31517542 2.53162739 4.05373821 4.74579066 2.22000962
 3.19471054 3.81632647 3.08769313 2.57609611 3.51837929 3.33828521
 2.78773392 3.72926195 2.30496826 3.51966958 1.9385404  5.04841101
 1.69872187 3.9668917  3.79284407 3.2262862  4.7088822  0.9226298
 2.08810228 4.40054442 2.69686885 4.42317231 4.14833943 2.82883433
 3.86939822 4.03690505 1.7606951  2.58717012 4.13278732 4.75588051
 3.58908168 2.8725224  4.41827381 5.03758585 4.16325514 1.65933784
 4.1829974  2.43478701 2.65883564 3.91228972 3.99736234 3.18914016
 2.97408537 5.34816009]
shape:(50,)

***中間層出力1***
[2.67792354 4.31517542 2.53162739 4.05373821 4.74579066 2.22000962
 3.19471054 3.81632647 3.08769313 2.57609611 3.51837929 3.33828521
 2.78773392 3.72926195 2.30496826 3.51966958 1.9385404  5.04841101
 1.69872187 3.9668917  3.79284407 3.2262862  4.7088822  0.9226298
 2.08810228 4.40054442 2.69686885 4.42317231 4.14833943 2.82883433
 3.86939822 4.03690505 1.7606951  2.58717012 4.13278732 4.75588051
 3.

二値分類(2-3-1ネットワーク）

In [16]:
# 重みとバイアスの初期値を設定
def init_network():
  network = {}
  network['W1'] = np.array([
    [0.1, 0.3, 0.5, 0.1, 0.3, 0.5, 0.1, 0.3, 0.5, 0.1],
    [0.1, 0.3, 0.5, 0.1, 0.3, 0.5, 0.1, 0.3, 0.5, 0.1],
    [0.1, 0.3, 0.5, 0.1, 0.3, 0.5, 0.1, 0.3, 0.5, 0.1],
    [0.1, 0.3, 0.5, 0.1, 0.3, 0.5, 0.1, 0.3, 0.5, 0.1],
    [0.1, 0.3, 0.5, 0.1, 0.3, 0.5, 0.1, 0.3, 0.5, 0.1]
  ])

  network['W2'] = np.random.rand(10, 20)
  network['W3'] = np.random.rand(20, 1)

  network['b1'] = np.random.rand(10)
  network['b2'] = np.random.rand(20)
  network['b3'] = np.random.rand(1)


  return network

# 順伝播処理
def forward(network, x):
  W1, W2, W3 = network['W1'], network['W2'], network['W3']
  b1, b2, b3 = network['b1'], network['b2'], network['b3']

  # 隠れ層1の総入力
  u1 = np.dot(x, W1) + b1
  # 隠れ層1の総出力
  z1 = functions.relu(u1)
  # 隠れ層2の総入力
  u2 = np.dot(z1, W2) + b2
  # 隠れ層2の総出力
  z2 = functions.relu(u2)

  u3 = np.dot(z2, W3) + b3
  z3 = functions.sigmoid(u3)
  y = z3

  print_vec('総入力1', u1)
  print_vec('中間層出力1', z1)
  print_vec('総入力2', u2)
  print_vec('出力', y)
  print('出力合計:' + str(np.sum(y)))

  return y, z1

In [17]:
# 入力値
x = np.array([1., 2., 2., 4., 5.])
network = init_network()
y, z1 = forward(network, x)

# 目標値出力
d = np.array([1])
# 誤差
loss = functions.cross_entropy_error(d, y)


print_vec('中間層出力', z1)
print_vec('出力', y)
print_vec('訓練データ', d)
print_vec('誤差', loss)

***総入力1***
[2.36880755 4.82617841 7.35384201 2.26560527 5.00833396 7.79923503
 2.39148112 4.66847012 7.24608791 1.85444506]
shape:(10,)

***中間層出力1***
[2.36880755 4.82617841 7.35384201 2.26560527 5.00833396 7.79923503
 2.39148112 4.66847012 7.24608791 1.85444506]
shape:(10,)

***総入力2***
[18.32492753 18.91388328 29.3420079  19.4586671  19.43217255 33.3893957
 26.82884614 26.21371536 25.04155337 24.80836775 24.52517681 29.02075827
 16.95967601 27.19258607 17.11053732 22.44891922 24.80177178 25.72661499
 22.85555818 21.64479776]
shape:(20,)

***出力***
[1.]
shape:(1,)

出力合計:1.0
***中間層出力***
[2.36880755 4.82617841 7.35384201 2.26560527 5.00833396 7.79923503
 2.39148112 4.66847012 7.24608791 1.85444506]
shape:(10,)

***出力***
[1.]
shape:(1,)

***訓練データ***
[1]
shape:(1,)

***誤差***
-9.999999505838704e-08
shape:()

